#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Namespace
metadata:
 name: #@ data.values.namespace
---
#@overlay/match by=overlay.not_op(overlay.subset({"kind":"Namespace"})),expects="1+"
---
metadata:
 #@overlay/match missing_ok=True
 namespace: #@ data.values.namespace
---
#@overlay/match by=overlay.subset({"kind":"Secret","metadata":{"name":"code-server"}})
---
data:
  password: #@ base64.encode(data.values.code_server_password) 
---
#@overlay/match by=overlay.subset({"kind":"Ingress","metadata":{"name":"code-server"}})
---
spec:
  rules:
  #@overlay/match by=overlay.index(0)
  - host: #@ data.values.code_server_host
---
#@overlay/match by=overlay.subset({"kind":"Pod","metadata":{"name":"code-server-test-connection"}})
#@overlay/remove
---

