#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argo-cd-selfsigned-issuer
  namespace: #@ data.values.namespace
spec:
  selfSigned: { }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd-ca
  namespace: #@ data.values.namespace
spec:
  commonName: argo-cd-ca
  isCA: true
  issuerRef:
    kind: Issuer
    name: argo-cd-selfsigned-issuer
  secretName: argo-cd-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argo-cd-ca-issuer
  namespace: #@ data.values.namespace
spec:
  ca:
    secretName: argo-cd-ca
