#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Namespace
metadata:
 name: #@ data.values.namespace
---
#@overlay/match by=overlay.not_op(overlay.subset({"kind":"Namespace"})),expects="1+"
---
metadata:
 #@overlay/match missing_ok=True
 namespace: #@ data.values.namespace
---
#@overlay/match by=overlay.subset({"kind":"Ingress","metadata":{"name":"gitea"}})
---
spec:
  rules:
  #@overlay/match by=overlay.index(0)
  - host: #@ data.values.gitea_host
  tls:
  #@overlay/match by=overlay.index(0)
  - hosts:
    #@overlay/match by=overlay.index(0)
    - #@ data.values.gitea_host
    secretName: #@ data.values.gitea_host
---
#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"gitea-memcached"}})
---
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          #@overlay/match by=overlay.index(0)
          - podAffinityTerm:
              namespaces:
              #@overlay/match by=overlay.index(0)
              - #@ data.values.namespace
---
#@overlay/match by=overlay.subset({"kind":"StatefulSet","metadata":{"name":"gitea-postgresql"}})
---
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          #@overlay/match by=overlay.index(0)
          - podAffinityTerm:
              namespaces:
              #@overlay/match by=overlay.index(0)
              - #@ data.values.namespace
---
#@overlay/match by=overlay.subset({"kind":"StatefulSet","metadata":{"name":"gitea"}})
---
spec:
  template:
    spec:
      initContainers:
      #@overlay/match by="name"
      - name: configure-gitea
        env:
        #@overlay/match by="name"
        - name: GITEA_ADMIN_PASSWORD
          value: #@ data.values.gitea_password
---
#@overlay/match by=overlay.subset({"kind":"Pod","metadata":{"name":"gitea-test-connection"}})
#@overlay/remove
---
#@overlay/match by=overlay.subset({"kind":"Secret","metadata":{"name":"gitea-inline-config"}})
---
stringData:
  #@overlay/match 
  #@yaml/text-templated-strings
  cache: |-
    ADAPTER=memcache
    ENABLED=true
    HOST=gitea-memcached.(@= data.values.namespace @).svc.cluster.local:11211
  #@yaml/text-templated-strings
  database: |-
    DB_TYPE=postgres
    HOST=gitea-postgresql.(@= data.values.namespace @).svc.cluster.local:5432
    NAME=gitea
    PASSWD=gitea
    USER=gitea
