apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: gitea.tkg.tanzu.1.15.10
spec:
  refName: gitea.tkg.tanzu
  version: 1.15.10
  releaseNotes: |
    Initial release of Gitea for Air-gapped env
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          default: gitea
          description: Namespace
        gitea_password:
          type: string
          default: VMware1!
          description: Default Password
        gitea_host:
          type: string
          default: example.com
          description: Hostname
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: oss-harbor.tkg.tanzu/my-project/gitea/bundle@sha256:adc2405b3ec6511d56446ab71ae707bc1e4cd526e1ec6752fdf84084ca10a484
      template:
      - ytt:
          paths:
          - ./config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
